/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios.consulta;

import clases.GoleadorJoinEquipo;
import static formularios.consulta.TablaPosiciones.tablaPosiciones;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import metodos.Cargar;
import metodos.CentralizarColumnasJTable;
import metodos.Leer;

/**
 *
 * @author Federico
 */
public class TablaGoleadores extends javax.swing.JDialog {

    private int idTorneo;
    private TableCellRenderer columnasCentralizadas = new CentralizarColumnasJTable();
    
    public TablaGoleadores(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public TablaGoleadores(javax.swing.JDialog parent, boolean modal, int idTorneo) {
        super(parent, modal);
        initComponents();
        this.idTorneo = idTorneo;
        setLocationRelativeTo(null);
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Tabla de Goleadores");
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
        // Personaliza el JTable              
        tablaGoleadores.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tablaGoleadores.getTableHeader().setOpaque(false);
        tablaGoleadores.getTableHeader().setBackground(new Color(255,153,0));
        tablaGoleadores.getTableHeader().setForeground(new Color(255,255,255));
        tablaGoleadores.setRowHeight(25);        
    }    
    
    private void propiedadesTabla(){
        
        tablaGoleadores.getColumnModel().getColumn(0).setCellRenderer(columnasCentralizadas);        
        tablaGoleadores.getColumnModel().getColumn(1).setCellRenderer(columnasCentralizadas);        
        tablaGoleadores.getColumnModel().getColumn(2).setCellRenderer(columnasCentralizadas);
        tablaGoleadores.getColumnModel().getColumn(3).setCellRenderer(columnasCentralizadas);        
        
        TableColumn columnaCero = tablaGoleadores.getColumnModel().getColumn(0);
        columnaCero.setMaxWidth(0);
        columnaCero.setMinWidth(0);
        columnaCero.setPreferredWidth(0);
        TableColumn columnaDos = tablaGoleadores.getColumnModel().getColumn(1);
        columnaDos.setMaxWidth(220);
        columnaDos.setMinWidth(220);
        columnaDos.setPreferredWidth(220);
        TableColumn columnaTres = tablaGoleadores.getColumnModel().getColumn(3);
        columnaTres.setMaxWidth(80);
        columnaTres.setMinWidth(80);
        columnaTres.setPreferredWidth(80);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaGoleadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane8.setBorder(null);

        tablaPosiciones = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaGoleadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaGoleadores.setGridColor(new java.awt.Color(255, 255, 255));
        tablaGoleadores.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaGoleadores.setRowHeight(25);
        tablaGoleadores.setSelectionBackground(new java.awt.Color(0, 112, 192));
        tablaGoleadores.setShowVerticalLines(false);
        tablaGoleadores.getTableHeader().setReorderingAllowed(false);
        tablaGoleadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGoleadoresMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tablaGoleadores);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaGoleadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGoleadoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaGoleadoresMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                        
        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();
        
        String tituloTablaGoleadores [] = new String[4];   
        tituloTablaGoleadores[0] = "ID";    
        tituloTablaGoleadores[1] = "Nombre";  
        tituloTablaGoleadores[2] = "Equipo";
        tituloTablaGoleadores[3] = "Gol/es";        
                
        GoleadorJoinEquipo idJugadorTablaGoleadores [] = miLeer.leerJugadoresDeTablaGoleadores(idTorneo);
        GoleadorJoinEquipo miGoleadorJoinEquipo [] = new GoleadorJoinEquipo[idJugadorTablaGoleadores.length];
        for(int i = 0; i < idJugadorTablaGoleadores.length; i++){            
            miGoleadorJoinEquipo[i] = miLeer.leerTablaGoleadores(idTorneo, idJugadorTablaGoleadores[i].getIdJugador());            
        }        
        GoleadorJoinEquipo aux = new GoleadorJoinEquipo();
        for(int i = 0; i < miGoleadorJoinEquipo.length; i++){
            for(int j = 0; j < (miGoleadorJoinEquipo.length-1); j++){
                if(miGoleadorJoinEquipo[j].getGolesJugador()< miGoleadorJoinEquipo[j+1].getGolesJugador()){                
                    aux = miGoleadorJoinEquipo[j+1];
                    miGoleadorJoinEquipo[j+1] = miGoleadorJoinEquipo[j];
                    miGoleadorJoinEquipo[j] = aux;
                }
            }            
        }        
        
        tablaGoleadores = miCargar.cargarTablaGoleadores(tablaGoleadores, miGoleadorJoinEquipo, tituloTablaGoleadores);
        
        propiedadesTabla();        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaGoleadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaGoleadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaGoleadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaGoleadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaGoleadores dialog = new TablaGoleadores(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JTable tablaGoleadores;
    // End of variables declaration//GEN-END:variables
}
