/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios.modificar;

import clases.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import metodos.Modificar;

/**
 *
 * @author Federico Melo
 */
public class ModificarContraseñaPerfil extends javax.swing.JDialog {

    private boolean mostrar = true;
    private Usuario miUsuario;
    
    public ModificarContraseñaPerfil(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Cambiar Contraseña");
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
    }     
    
    public ModificarContraseñaPerfil(javax.swing.JDialog parent, boolean modal, Usuario miUsuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);        
        this.miUsuario = miUsuario;
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Cambiar Contraseña de " +miUsuario.getNombreUsuario()+ " "+miUsuario.getApellidoUsuario());
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_mostrarPassword = new javax.swing.JTextField();
        btn_mostrarPassword = new javax.swing.JButton();
        btn_IniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Contraseña:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, 24));

        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 224, 29));

        txt_mostrarPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_mostrarPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mostrarPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_mostrarPassword.setPreferredSize(new java.awt.Dimension(2, 28));
        jPanel2.add(txt_mostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 224, 29));

        btn_mostrarPassword.setBackground(new java.awt.Color(255, 255, 255));
        btn_mostrarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eye (1).png"))); // NOI18N
        btn_mostrarPassword.setBorder(null);
        btn_mostrarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mostrarPasswordMouseEntered(evt);
            }
        });
        btn_mostrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 30, 28));

        btn_IniciarSesion.setBackground(new java.awt.Color(255, 153, 0));
        btn_IniciarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_IniciarSesion.setText("Aceptar");
        btn_IniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btn_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMouseExited(evt);
            }
        });
        btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 225, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMouseEntered

    }//GEN-LAST:event_btn_IniciarSesionMouseEntered

    private void btn_IniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMouseExited
 
    }//GEN-LAST:event_btn_IniciarSesionMouseExited

    private void btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarSesionActionPerformed
        
        if(!txt_password.getText().trim().isEmpty()){
                                   
            Modificar miModificar = new Modificar();                
                
            miUsuario.setPassword(txt_password.getText().trim());
            miModificar.modificarContraseñaUsuario(miUsuario);            
            dispose();                       
            
        }else{
            
            new alertas.AlertWarning(this, true, "Debe rellenar colocar una contraseña").setVisible(true);                                                       
            
        }        
        
    }//GEN-LAST:event_btn_IniciarSesionActionPerformed

    private void btn_mostrarPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarPasswordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mostrarPasswordMouseEntered

    private void btn_mostrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarPasswordActionPerformed
                
        if(mostrar){
            txt_mostrarPassword.setVisible(true);
            txt_password.setVisible(false);
            txt_mostrarPassword.setText(txt_password.getText());
            mostrar = false;
        }else{
            txt_password.setVisible(true);
            txt_mostrarPassword.setVisible(false);
            txt_password.setText(txt_mostrarPassword.getText());
            mostrar = true;
        }
        
    }//GEN-LAST:event_btn_mostrarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseñaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseñaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseñaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseñaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarContraseñaPerfil dialog = new ModificarContraseñaPerfil(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IniciarSesion;
    private javax.swing.JButton btn_mostrarPassword;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_mostrarPassword;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
