/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.EquipoJoinJugador;
import clases.Jugador;
import com.placeholder.PlaceHolder;
import formularios.modificar.ModificarEquipo;
import static formularios.modificar.ModificarEquipo.DefaultTableModel;
import static formularios.modificar.ModificarEquipo.tablaJugadorEquipo;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import metodos.Cargar;
import metodos.CentralizarColumnasJTable;
import metodos.Guardar;
import metodos.Leer;

/**
 *
 * @author Federico
 */
public class AgregarJugadorModificarEquipo extends javax.swing.JDialog {

    private TableCellRenderer columnasCentralizadas = new CentralizarColumnasJTable();
    private String titulos[] = new String[8];
    private int idUsuario;
    private int idEquipo;

    public AgregarJugadorModificarEquipo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AgregarJugadorModificarEquipo(javax.swing.JDialog parent, boolean modal, int idUsuario, int idEquipo) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
        this.idEquipo = idEquipo;
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Alta Equipo");
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
        PlaceHolder miPlaceHolder = new PlaceHolder(txt_buscar, " Buscar Jugador por Nombre, Apellido o DNI");
        cmbDatos.setBackground(Color.WHITE);
        tablaJugadorDos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tablaJugadorDos.getTableHeader().setOpaque(false);
        tablaJugadorDos.getTableHeader().setBackground(new Color(255, 153, 0));
        tablaJugadorDos.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    public void cargarTabla(int idUsuario) {
        titulos[0] = "ID";
        titulos[1] = "Nombre";
        titulos[2] = "Apellido";
        titulos[3] = "DNI";
        titulos[4] = "Domicilio";
        titulos[5] = "Teléfono";
        titulos[6] = "Estatura";
        titulos[7] = "Posición";

        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();
        tablaJugadorDos = miCargar.cargarJugador(tablaJugadorDos, miLeer.leerJugador(idUsuario), titulos);
    }

    public void cargarTablaModificarEquipo(int idUsuario) {
        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();

        String titulos[] = new String[8];
        titulos[0] = "ID";
        titulos[1] = "Nombre";
        titulos[2] = "Apellido";
        titulos[3] = "DNI";
        titulos[4] = "Domicilio";
        titulos[5] = "Teléfono";
        titulos[6] = "Estatura";
        titulos[7] = "Posición";

        DefaultTableModel.setColumnIdentifiers(titulos);
        tablaJugadorEquipo.setModel(DefaultTableModel);

        Jugador miJugador[] = miLeer.leerEquiposRelacionJugador(idUsuario, idEquipo);

        tablaJugadorEquipo = miCargar.cargarJugador(tablaJugadorEquipo, miJugador, titulos);
    }

    private void propiedadesTabla() {

        tablaJugadorDos.getColumnModel().getColumn(1).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(2).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(3).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(4).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(5).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(6).setCellRenderer(columnasCentralizadas);
        tablaJugadorDos.getColumnModel().getColumn(7).setCellRenderer(columnasCentralizadas);

        TableColumn columnaCero = tablaJugadorDos.getColumnModel().getColumn(0);
        columnaCero.setMaxWidth(0);
        columnaCero.setMinWidth(0);
        columnaCero.setPreferredWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemAgregarJugador = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        cmbDatos = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaJugadorDos = new javax.swing.JTable();

        jPopupMenu1.setBackground(new java.awt.Color(255, 255, 255));

        itemAgregarJugador.setBackground(new java.awt.Color(255, 255, 255));
        itemAgregarJugador.setText("Agregar Jugador");
        itemAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarJugadorActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemAgregarJugador);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccionar Jugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        txt_buscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_buscar.setAlignmentX(0.8F);
        txt_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setPreferredSize(new java.awt.Dimension(105, 28));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        cmbDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "DNI" }));
        cmbDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        cmbDatos.setFocusable(false);
        cmbDatos.setPreferredSize(new java.awt.Dimension(77, 30));
        cmbDatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDatosItemStateChanged(evt);
            }
        });
        cmbDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDatosActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscadorDos.png"))); // NOI18N
        jToggleButton1.setText("  Buscar");
        jToggleButton1.setBorder(null);
        jToggleButton1.setPreferredSize(new java.awt.Dimension(105, 28));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        tablaJugadorDos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaJugadorDos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaJugadorDos.setComponentPopupMenu(jPopupMenu1);
        tablaJugadorDos.setGridColor(new java.awt.Color(255, 255, 255));
        tablaJugadorDos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaJugadorDos.setRowHeight(25);
        tablaJugadorDos.setSelectionBackground(new java.awt.Color(0, 112, 192));
        tablaJugadorDos.setShowVerticalLines(false);
        tablaJugadorDos.getTableHeader().setReorderingAllowed(false);
        tablaJugadorDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJugadorDosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaJugadorDos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(cmbDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_buscar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        txt_buscar.setText("");
        cargarTabla(idUsuario);
        propiedadesTabla();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void cmbDatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDatosItemStateChanged

    }//GEN-LAST:event_cmbDatosItemStateChanged

    private void cmbDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDatosActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        titulos[0] = "ID";
        titulos[1] = "Nombre";
        titulos[2] = "Apellido";
        titulos[3] = "DNI";
        titulos[4] = "Domicilio";
        titulos[5] = "Teléfono";
        titulos[6] = "Estatura";
        titulos[7] = "Posición";
        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();

        if (cmbDatos.getSelectedItem().equals("Nombre")) {
            tablaJugadorDos = miCargar.cargarJugador(tablaJugadorDos, miLeer.buscarJugadoresPorNombre(txt_buscar.getText().trim(), idUsuario), titulos);
        } else if (cmbDatos.getSelectedItem().equals("Apellido")) {
            tablaJugadorDos = miCargar.cargarJugador(tablaJugadorDos, miLeer.buscarJugadoresPorApellido(txt_buscar.getText().trim(), idUsuario), titulos);
        } else if (cmbDatos.getSelectedItem().equals("DNI")) {
            tablaJugadorDos = miCargar.cargarJugador(tablaJugadorDos, miLeer.buscarJugadoresPorDni(txt_buscar.getText().trim(), idUsuario), titulos);
        }

        propiedadesTabla();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tablaJugadorDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugadorDosMouseClicked

    }//GEN-LAST:event_tablaJugadorDosMouseClicked

    private void itemAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarJugadorActionPerformed

        Jugador miJugador = new Jugador();
        miJugador.setIdJugador(Integer.parseInt(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 0).toString()));
        miJugador.setNombreJugador(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 1).toString());
        miJugador.setApellidoJugador(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 2).toString());
        miJugador.setDniJugador(Long.parseLong(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 3).toString()));
        miJugador.setDomicilioJugador(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 4).toString());
        miJugador.setTelefonoJugador(Long.parseLong(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 5).toString()));
        miJugador.setEstaturaJugador(Double.parseDouble(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 6).toString()));
        miJugador.setPosicionJugador(tablaJugadorDos.getValueAt(tablaJugadorDos.getSelectedRow(), 7).toString());
        
        String miJugadorTabla[] = new String[8];
        miJugadorTabla[0] = String.valueOf(miJugador.getIdJugador());
        miJugadorTabla[1] = miJugador.getNombreJugador();
        miJugadorTabla[2] = miJugador.getApellidoJugador();
        miJugadorTabla[3] = String.valueOf(miJugador.getDniJugador());
        miJugadorTabla[4] = miJugador.getDomicilioJugador();
        miJugadorTabla[5] = String.valueOf(miJugador.getTelefonoJugador());
        miJugadorTabla[6] = String.valueOf(miJugador.getEstaturaJugador());
        miJugadorTabla[7] = miJugador.getPosicionJugador();
        
        Guardar miGuardar = new Guardar();        
        EquipoJoinJugador miEquipoJoinJugador = new EquipoJoinJugador();
        miEquipoJoinJugador.setIdEquipo(idEquipo);
        miEquipoJoinJugador.setIdJugador(miJugador.getIdJugador());
        miEquipoJoinJugador.setEstadoEquipoJoinJugador("alta");
        miGuardar.guardarEquipoJoinJugador(miEquipoJoinJugador);            

        new alertas.AlertSuccess(this, true, "El jugador se ha agregado correctamente").setVisible(true);                                           

    }//GEN-LAST:event_itemAgregarJugadorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        cargarTabla(idUsuario);
        propiedadesTabla();

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarJugadorModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarJugadorModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarJugadorModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarJugadorModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarJugadorModificarEquipo dialog = new AgregarJugadorModificarEquipo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDatos;
    private javax.swing.JMenuItem itemAgregarJugador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JTable tablaJugadorDos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
