/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Equipo;
import com.placeholder.PlaceHolder;
import formularios.Altas.NuevoTorneo;
import static formularios.Altas.NuevoTorneo.dft;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import metodos.Cargar;
import metodos.CentralizarColumnasJTable;
import metodos.Leer;

/**
 *
 * @author Federico
 */
public class BuscarEquipoJoinTorneo extends javax.swing.JDialog {

    private TableCellRenderer columnasCentralizadas = new CentralizarColumnasJTable();
    private String titulos [] = new String[4];
    private int idUsuario;
    
    public BuscarEquipoJoinTorneo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        PlaceHolder miPlaceHolder = new PlaceHolder(txt_buscar, "Buscar Equipo");
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Agregar Equipo ");
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
        tablaEquipoDos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tablaEquipoDos.getTableHeader().setOpaque(false);
        tablaEquipoDos.getTableHeader().setBackground(new Color(255,153,0));
        tablaEquipoDos.getTableHeader().setForeground(new Color(255,255,255));        
    }
    
    public BuscarEquipoJoinTorneo(javax.swing.JDialog parent, boolean modal, int idUsuario) {
        super(parent, modal);
        initComponents();
        this.idUsuario = idUsuario;
        setLocationRelativeTo(null);
        PlaceHolder miPlaceHolder = new PlaceHolder(txt_buscar, " Buscar por nombre de Equipo");
        // Título de la Ventana
        setTitle("PitMu SOFTWARE - Agregar Equipo ");
        // Icono para el Sistema
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
        tablaEquipoDos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tablaEquipoDos.getTableHeader().setOpaque(false);
        tablaEquipoDos.getTableHeader().setBackground(new Color(255,153,0));
        tablaEquipoDos.getTableHeader().setForeground(new Color(255,255,255));        
    }    
    
    private void cargarTabla(int idUsuario){
        
        titulos[0] = "ID";
        titulos[1] = "Nombre";
        titulos[2] = "Estadio";
        titulos[3] = "Dirección";
        
        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();
        miCargar.cargarEquipos(tablaEquipoDos, miLeer.leerEquipos(idUsuario), titulos);
        
    }
    
    private void propiedadesTabla(){                
        
        tablaEquipoDos.getColumnModel().getColumn(1).setCellRenderer(columnasCentralizadas);
        tablaEquipoDos.getColumnModel().getColumn(2).setCellRenderer(columnasCentralizadas);
        tablaEquipoDos.getColumnModel().getColumn(3).setCellRenderer(columnasCentralizadas);                                        
        
        TableColumn columnaCero = tablaEquipoDos.getColumnModel().getColumn(0);
        columnaCero.setMaxWidth(0);
        columnaCero.setMinWidth(0);
        columnaCero.setPreferredWidth(0);        
               
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemAgregarEquipo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaEquipoDos = new javax.swing.JTable();

        jPopupMenu1.setBackground(new java.awt.Color(255, 255, 255));

        itemAgregarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        itemAgregarEquipo.setText("Agregar Equipo");
        itemAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEquipoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemAgregarEquipo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccionar Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        txt_buscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_buscar.setAlignmentX(0.8F);
        txt_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setPreferredSize(new java.awt.Dimension(105, 28));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscadorDos.png"))); // NOI18N
        jToggleButton1.setText("  Buscar");
        jToggleButton1.setBorder(null);
        jToggleButton1.setPreferredSize(new java.awt.Dimension(105, 28));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        tablaEquipoDos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaEquipoDos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaEquipoDos.setComponentPopupMenu(jPopupMenu1);
        tablaEquipoDos.setGridColor(new java.awt.Color(255, 255, 255));
        tablaEquipoDos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaEquipoDos.setRowHeight(25);
        tablaEquipoDos.setSelectionBackground(new java.awt.Color(0, 112, 192));
        tablaEquipoDos.setShowVerticalLines(false);
        tablaEquipoDos.getTableHeader().setReorderingAllowed(false);
        tablaEquipoDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquipoDosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaEquipoDos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txt_buscar))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla(idUsuario);
        propiedadesTabla();
    }//GEN-LAST:event_formWindowOpened

    private void itemAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEquipoActionPerformed
        
        Equipo miEquipo = new Equipo();
        miEquipo.setIdEquipo(Integer.parseInt(tablaEquipoDos.getValueAt(tablaEquipoDos.getSelectedRow(), 0).toString()));
        miEquipo.setNombreEquipo(tablaEquipoDos.getValueAt(tablaEquipoDos.getSelectedRow(), 1).toString());
        miEquipo.setNombreEstadioEquipo(tablaEquipoDos.getValueAt(tablaEquipoDos.getSelectedRow(), 2).toString());
        miEquipo.setDireccionEstadioEquipo(tablaEquipoDos.getValueAt(tablaEquipoDos.getSelectedRow(), 3).toString());
        
        String miEquipoTabla [] = new String [4];
        miEquipoTabla[0] = String.valueOf(miEquipo.getIdEquipo());
        miEquipoTabla[1] = miEquipo.getNombreEquipo();
        miEquipoTabla[2] = miEquipo.getNombreEstadioEquipo();
        miEquipoTabla[3] = miEquipo.getDireccionEstadioEquipo();
        
        NuevoTorneo.dft.addRow(miEquipoTabla);
        NuevoTorneo.tablaEquipo.setModel(dft);

        new alertas.AlertSuccess(this, true, "El equipo se ha agregado correctamente").setVisible(true);                                           
        
    }//GEN-LAST:event_itemAgregarEquipoActionPerformed

    private void tablaEquipoDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquipoDosMouseClicked

    }//GEN-LAST:event_tablaEquipoDosMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        titulos[0] = "ID";
        titulos[1] = "Nombre";
        titulos[2] = "Estadio";
        titulos[3] = "Dirección";
        
        Leer miLeer = new Leer();
        Cargar miCargar = new Cargar();
        miCargar.cargarEquiposDinamicamente(tablaEquipoDos, miLeer.leerEquiposPorNombre(txt_buscar.getText().trim(), idUsuario), titulos);
        
        propiedadesTabla();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
        txt_buscar.setText("");
        cargarTabla(idUsuario);
        propiedadesTabla();
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipoJoinTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipoJoinTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipoJoinTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipoJoinTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarEquipoJoinTorneo dialog = new BuscarEquipoJoinTorneo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregarEquipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JTable tablaEquipoDos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
